/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import GameModels.User;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Map;
import java.util.Vector;
import javafx.util.Pair;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vu Tien Hoa
 */
public class Rank extends javax.swing.JFrame {

    /**
     * Creates new form Rank
     */
    public Rank() {
        initComponents();
        btnWin.setName("win");
        btnScore.setName("score");
        btnLost.setName("lost");
        setLocationRelativeTo(null);
    }
    public void addListenBtn(ActionListener l){
        btnWin.addActionListener(l);
        btnLost.addActionListener(l);
        btnScore.addActionListener(l);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRank = new javax.swing.JTable();
        btnScore = new javax.swing.JButton();
        btnWin = new javax.swing.JButton();
        btnLost = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rank Page");

        tableRank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "User Name", "num"
            }
        ));
        jScrollPane1.setViewportView(tableRank);

        btnScore.setText("Score");

        btnWin.setText("win");

        btnLost.setText("lost");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGap(224, 224, 224))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(144, 144, 144)
                            .addComponent(btnScore)
                            .addGap(139, 139, 139)
                            .addComponent(btnWin)
                            .addGap(131, 131, 131)
                            .addComponent(btnLost))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnScore)
                    .addComponent(btnWin)
                    .addComponent(btnLost))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void showRank(ArrayList<Pair<String, String>> list){
        DefaultTableModel m = (DefaultTableModel) tableRank.getModel();
        m.setRowCount(0);
        int cnt=1;
        for(Pair<String,String> p :list){
            Vector<String> v = new Vector();
            v.add(String.valueOf(cnt++));
            v.add(p.getKey());
            v.add(p.getValue());
            m.addRow(v);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLost;
    private javax.swing.JButton btnScore;
    private javax.swing.JButton btnWin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRank;
    // End of variables declaration//GEN-END:variables
}
